#For changes to reflect on steamUI, restart steam-patch, and restart steam. (Current mitigation)

main_enabled = true
tdp_control = true
gpu_control = true
max_tdp = 25
max_gpu = 2800

#ROG ALLY specific toggles
legacy_tdp = false #true = ryzenadj, false = new method
mapper = true #Enable disable the QAM and Steam button mapping
#Experimental
auto_nkey_recovery = false #Attempts to suspend and resume the device if NKEY is lost
