#For changes to reflect on steamUI, restart steam-patch, and restart steam. (Current mitigation)
main_enabled = true
tdp_control = true
gpu_control = true
max_tdp = 30               #If using smokeless bios you can push this higher
max_gpu = 2700

#Feature toggles
legacy_tdp = false         #true = ryzenadj, false = ACPI ROG ALLY METHOD
mapper = true              #Enable disable the QAM and Steam button mapping
spoof_glyphs = true        #Enable to change PS/Xbox buttons to match SD including Steam Menu and Option menu


#Experimental ROG ALLY ONLY
auto_nkey_recovery = false #Attempts to suspend and resume the device if NKEY is lost
