name: Rust Build

on:
  push:
    branches: [ rust ]
  pull_request:
    branches: [ rust ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - name: Strip Debug Symbols
        run: strip -s target/x86_64-unknown-linux-gnu/release/ally-steam-patch

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ally-steam-patch
          path: target/x86_64-unknown-linux-gnu/release/ally-steam-patch
